import {
  BLACK,
  BLUE,
  BLUE_DARK,
  BLUE_HIGHLIGHT,
  BLUE_HIGHLIGHT_LIGHT,
  BLUE_LIGHT,
  BLUE_SKY,
  BLUE_SKY_DARK,
  BLUE_TEXT,
  BLUE_TRANSPARENT,
  DARK_GRAY_LINES,
  DBT_ORANGE,
  DBT_ORANGE_TRANSPARENT,
  DBT_ORANGE_TRANSPARENT_DARK,
  GRAY,
  GRAY_HIGHLIGHT,
  GRAY_LINES,
  GREEN,
  GREY100,
  GREY200,
  GREY300,
  GREY400,
  GREY500,
  LIGHT,
  LIME,
  LIME_DARK,
  LIME_TEXT,
  LIME_TRASPARENT,
  LIME_XLIGHT,
  NAVY,
  PEACH,
  PINK,
  PINK_TRANSPARENT,
  PURPLE,
  PURPLE2,
  PURPLE_DARK,
  PURPLE_DISABLED,
  PURPLE_HIGHLIGHT,
  PURPLE_LIGHT,
  PURPLE_TRANSPARENT,
  RED,
  RED_HIGHLIGHT,
  RED_LIGHT,
  RED_XLIGHT,
  SILVER,
  WHITE,
  YELLOW,
  YELLOW_LIGHT,
  YELLOW_TRANSPARENT,
} from '../colors/main';
import {
  DARK_CONTENT_ACTIVE,
  DARK_CONTENT_DEFAULT,
  DARK_CONTENT_DISABLED,
  DARK_CONTENT_INVERTED,
  DARK_CONTENT_MUTED,
} from '../colors/content';

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  type: 'light',
  accent: {
    alert: '#F6540B',
    blue: BLUE_DARK,
    blueLight: BLUE_TRANSPARENT,
    contentDefaultTransparent: 'rgba(0, 0, 0, 0.3)',
    cyan: '#65E3FF',
    cyanLight: 'rgba(101, 227, 255, 0.3)',
    cyanTransparent: 'rgba(101, 227, 255, 0.12)',
    dbt: DBT_ORANGE,
    dbtDark: DBT_ORANGE_TRANSPARENT_DARK,
    dbtLight: DBT_ORANGE_TRANSPARENT,
    info: '#00ABFF',
    infoTransparent: 'rgba(0, 171, 255, 0.5)',
    negative: '#FF1E59',
    negativeTransparent: 'rgba(255, 30, 89, 0.3)',
    pink: PINK,
    pinkLight: PINK_TRANSPARENT,
    positive: '#00A81A',
    primaryTransparent: 'rgb(155, 108, 167, 0.5)',
    purple: PURPLE,
    purpleLight: PURPLE_TRANSPARENT,
    rose: '#D1A2AB',
    roseLight: 'rgba(209, 162, 171, 0.5)',
    sky: BLUE_SKY,
    skyLight: 'rgba(106, 161, 224, 0.5)',
    teal: '#00B4CC',
    tealLight: 'rgba(0, 180, 204, 0.5)',
    warning: '#DD9900',
    warningTransparent: 'rgba(221, 153, 0, 0.5)',
    yellow: YELLOW,
    yellowLight: YELLOW_TRANSPARENT,
  },
  background: {
    blackTransparent: 'rgba(0, 0, 0, 0.3)',
    blackTransparentDark: 'rgba(0, 0, 0, 0.6)',
    chartBlock: WHITE,
    codeArea: GREY100,
    codeTextarea: WHITE,
    content: WHITE,
    danger: RED_XLIGHT,
    dark: GRAY,
    dashboard: SILVER,
    dashboardTransparent: 'rgba(249, 250, 252, 0.1)',
    header: WHITE,
    menu: NAVY,
    muted: SILVER,
    navigation: '#EDEDED',
    output: WHITE,
    page: SILVER,
    panel: WHITE,
    panelTransparent: 'rgba(255, 255, 255, 0.7)',
    popup: WHITE,
    row: LIGHT,
    row2: WHITE,
    scrollbarThumb: 'rgba(0, 0, 0, 0.2)',
    scrollbarThumbHover: 'rgba(0, 0, 0, 0.4)',
    scrollbarTrack: 'rgba(0, 0, 0, 0.05)',
    success: LIME_XLIGHT,
    successLight: LIME_TRASPARENT,
    table: WHITE,
    tag: GREY100,
  },
  borders: {
    button: GREY200,
    contrast: BLACK,
    danger: RED,
    dark: GRAY_LINES,
    darkLight: SILVER,
    info: YELLOW,
    light: '#E7E8EA',
    medium: '#D5D7DC',
    medium2: '#CFCBCB',
    success: GREEN,
  },
  brand: {
    earth100: '#C6EEDB',
    earth200: '#9DDFBF',
    earth300: '#6BBF96',
    earth400: '#37A46F',
    earth400Transparent: 'rgba(55, 164, 111, 0.4)',
    earth500: '#00954C',
    energy100: '#FFF4BA',
    energy200: '#FFED92',
    energy300: '#FFE662',
    energy400: '#FFDA19',
    energy400Transparent: 'rgba(255, 218, 25, 0.04)',
    energy500: '#F6C000',
    fire100: '#FFD7E0',
    fire200: '#FFA3B9',
    fire300: '#FF547D',
    fire400: '#FF144D',
    fire400Transparent: 'rgba(255, 20, 77, 0.4)',
    fire500: '#EB0032',
    stone100: '#F3E6D7',
    stone200: '#E3D4C2',
    stone400: '#BFA78B',
    stone500: '#AF8859',
    water100: '#BDCEFF',
    water200: '#81A1FF',
    water300: '#517DFF',
    water400: '#2A60FE',
    water400Transparent: 'rgba(42, 96, 254, 0.4)',
    water500: '#0F4CFF',
    wind100: '#EEEAFF',
    wind200: '#CCC1F4',
    wind300: '#A698DD',
    wind400: '#6B50D7',
    wind400SuperTransparent: 'rgba(107, 80, 215, 0.12)',
    wind400Transparent: 'rgba(107, 80, 215, 0.4)',
    wind500: '#4E32BC',
  },
  chart: {
    backgroundDanger: RED_LIGHT,
    backgroundPrimary: PURPLE_LIGHT,
    backgroundSecondary: RED_LIGHT,
    backgroundTertiary: BLUE_HIGHLIGHT_LIGHT,
    button1: BLUE_DARK,
    button2: YELLOW,
    button3: LIME,
    button4: PINK,
    button5: PEACH,
    danger: RED,
    lines: '#9B6CA7',
    primary: PURPLE,
    secondary: RED,
    tertiary: BLUE_HIGHLIGHT,
  },
  content: {
    active: BLACK,
    default: BLACK,
    disabled: BLACK,
    inverted: WHITE,
    muted: BLACK,
  },
  contentInverted: {
    active: WHITE,
  },
  elevation: {
    visualizationAccent: '#996CFF',
    visualizationAccentAlt: '#C1ACF7',
  },
  feature: {
    active: PURPLE_HIGHLIGHT,
    disabled: PURPLE_DISABLED,
  },
  icons: {
    neutral: '#787878',
  },
  interactive: {
    activeBorder: BLACK,
    blackBackgroundTransparent: 'rgba(0, 0, 0, 0.3)',
    checked: PURPLE_LIGHT,
    dangerBorder: RED,
    defaultBackground: WHITE,
    defaultBackgroundTransparent: 'rgba(255, 255, 255, 0.5)',
    defaultBorder: GRAY_LINES,
    disabledBorder: GRAY,
    focusBackground: GRAY,
    focusBorder: BLUE_HIGHLIGHT,
    hoverBackground: SILVER,
    hoverBackgroundTransparent: 'rgba(230, 230, 230, 0.5)',
    hoverBlackBackgroundTransparent: 'rgba(0, 0, 0, 0.1)',
    hoverBorder: DARK_GRAY_LINES,
    hoverOverlay: 'rgba(0, 0, 0, 0.05)',
    linkPrimary: BLUE,
    linkPrimaryHover: BLUE_DARK,
    linkPrimaryLight: BLUE_LIGHT,
    linkSecondary: PURPLE,
    linkSecondaryDisabled: PURPLE_LIGHT,
    linkText: BLUE_SKY_DARK,
    linkTextLight: BLUE_SKY,
    purple: PURPLE2,
    rowHoverBackground: 'rgba(0, 0, 0, 0.03)',
    transparent: 'rgba(0, 0, 0, 0)',
  },
  loader: {
    color: LIME_DARK,
    colorInverted: '#EB0032',
  },
  logo: {
    color: BLUE_DARK,
  },
  monotone: {
    black: BLACK,
    blackTransparent: 'rgba(0, 0, 0, 0.3)',
    gray: GRAY,
    grey100: '#F2F2F2',
    grey200: '#D5D7DC',
    grey300: '#B4B8C0',
    grey400: '#70747C',
    grey500: '#28292C',
    purple: PURPLE,
    white: WHITE,
    whiteTransparent: 'rgba(255, 255, 255, 0.6)',
  },
  neutral: {
    n100: '#E7E8EA',
    n200: '#D8DADE',
    n300: '#CBCCD0',
    n400: '#BCBEC4',
    n500: '#AEB0B6',
  },
  progress: {
    negative: RED,
    positive: PURPLE,
  },
  shadow: {
    base: '0 4px 12px rgba(0, 0, 0, 0.1)',
    frame: '0 2px 8px rgba(0, 0, 0, 0.08)',
    menu: '0 4px 12px rgba(0, 0, 0, 0.12)',
    popup: '0 8px 16px rgba(0, 0, 0, 0.12)',
    small: '0 2px 4px rgba(0, 0, 0, 0.05)',
    window: '0 12px 24px rgba(0, 0, 0, 0.15)',
  },
  status: {
    negative: RED,
    positive: LIME_TEXT,
  },
  text: {
    fileBrowser: GREY500,
  },
};
